### ISSUE TITLE
not working now please help me out 

### ISSUE THREAD

**Issue by govindowlok0** [PtPrashantTripathi/linkpe#1]
i create valid upi and make upi paymnet link , n try to pay with phonepe,paytm but they are show upi limit is done in paytm upi 
and phonepe error is sowing technical issue but i did't do any upi payment today i try with different bank and different upi id

**Comment by PtPrashantTripathi** [comment]
It's not phone pe or my website error it's bank issue, they diffine daily UPI Payment limits

**Comment by govindowlok0** [comment]
can you check your app self please

**Comment by PtPrashantTripathi** [comment]
Alredy tested that's why saying, there is no insect in it

**Comment by PtPrashantTripathi** [comment]
Do one thing fork this code and check it your self, you find any bug and of can resolve it, send me a bug report and pull request
