### ISSUE TITLE
A successful payment response.

### ISSUE THREAD

**Issue by MelloB1989** [PtPrashantTripathi/linkpe#10]
Hello, I am a web developer. I am building my own marketplace and your gateway alternative is amazing! The only thing missing is that it doesn't give a response if the payment was successful or not to continue the transaction.

**Comment by guru4uu** [comment]
> Hello, I am a web developer. I am building my own marketplace and your gateway alternative is amazing! The only thing missing is that it doesn't give a response if the payment was successful or not to continue the transaction.

Same issue here brother thanks i hope developer do something for this issue

**Comment by PtPrashantTripathi** [comment]
Last month, the Delhi cyber police requested me to shut down this website because scammers were using it to deceive people. Despite being an open source website, it was being misused for fraudulent activities, and it was necessary to take action to protect innocent victims.
