### ISSUE TITLE
bro the site is not working check it https://ptprashanttripathi.github.io/linkpe/?pa=6294303922@paytm&pn=MDAFTAB&amt=500

### ISSUE THREAD

**Issue by rthjrsthr** [PtPrashantTripathi/linkpe#11]

**Comment by PtPrashantTripathi** [comment]
*Last month, the Delhi cyber police requested me to shut down this website because scammers were using it to deceive people. Despite being an open source website, it was being misused for fraudulent activities, and it was necessary to take action to protect innocent victims.*
