### ISSUE TITLE
Configure Payment App

### ISSUE THREAD

**Issue by zeeshanibs** [PtPrashantTripathi/linkpe#3]
Can you also provide an option to set the payment app option like google pay, phone pe, 
Currently by default WhatsApp payment is getting opened on click of the link

**Comment by PtPrashantTripathi** [comment]
https://user-images.githubusercontent.com/26687933/131973831-8beff657-13dd-4208-b9cd-2bafc7ef335f.mp4

In my set-up it's working fine
