### ISSUE TITLE
Amount not getting populated

### ISSUE THREAD

**Issue by cdharma** [PtPrashantTripathi/linkpe#4]
Hey Prashant, 
Thanks for sharing & great API. 

When I am trying to scan the QR code the amount is not getting auto-populated. I had to enter the amount again. 
It is picking the UPI id automatically though. For example, when I tried to scan a generated QR code, here is what I get. You can see it has picked UPI id but I need to enter the amount again.

![image](https://user-images.githubusercontent.com/8599454/136786965-6ba2682b-1eae-49ee-a7ac-5ef9da71966f.png)

Is there a way the UPI app can automatically pick the amount.

**Comment by PtPrashantTripathi** [comment]
Issue has been fixed
